In [1]:
from gensim.test.utils import common_texts
from gensim.models import TfidfModel, LdaModel, LsiModel
from gensim.corpora import Dictionary

In [2]:
common_texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]

# 一、数据加载

In [4]:
# 构建字典
common_dictionary = Dictionary(common_texts)
# 各个文本对应的词袋法的值
common_corpus = [common_dictionary.doc2bow(text) for text in common_texts]
print("原始数据:\n{}".format(common_texts))
print("\n词袋法后的值:\n{}".format(common_corpus))
print(f"文本数目:{len(common_texts)}")
print(f"去重后单词数目:{len(common_dictionary)}")

原始数据:
[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]

词袋法后的值:
[[(0, 1), (1, 1), (2, 1)], [(0, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)], [(2, 1), (5, 1), (7, 1), (8, 1)], [(1, 1), (5, 2), (8, 1)], [(3, 1), (6, 1), (7, 1)], [(9, 1)], [(9, 1), (10, 1)], [(9, 1), (10, 1), (11, 1)], [(4, 1), (10, 1), (11, 1)]]
文本数目:9
去重后单词数目:12
Dictionary<12 unique tokens: ['computer', 'human', 'interface', 'response', 'survey']...>


In [8]:
other_texts = [
    ['computer', 'time', 'graph'],  # 文本1
    ['survey', 'response', 'eps'],  # 文本2
    ['human', 'system', 'computer']  # 文本3
]
other_corpus = [common_dictionary.doc2bow(text) for text in other_texts]
print("测试数据对应的词袋法的值:\n{}".format(other_corpus))

测试数据对应的词袋法的值:
[[(0, 1), (6, 1), (10, 1)], [(3, 1), (4, 1), (8, 1)], [(0, 1), (1, 1), (5, 1)]]


# 二、TF-IDF Model

In [9]:
# 模型构建
model = TfidfModel(corpus=common_corpus)

In [10]:
# 预测
vectors = model[other_corpus]
for vector in vectors:
    print(vector)

[(0, np.float64(0.6282580468670046)), (6, np.float64(0.6282580468670046)), (10, np.float64(0.45889394536615247))]
[(3, np.float64(0.5773502691896257)), (4, np.float64(0.5773502691896257)), (8, np.float64(0.5773502691896257))]
[(0, np.float64(0.6282580468670046)), (1, np.float64(0.6282580468670046)), (5, np.float64(0.45889394536615247))]


# 三、LDA Model

In [11]:
# 模型构建&训练
model = LdaModel(common_corpus, num_topics=5)

In [12]:
# 模型保存
model.save('./datas/lda_model.pkl')

In [23]:
# 模型加载
lda = LdaModel.load('./datas/lda_model.pkl')

In [24]:
# 模型结果获取(文本向量)
vectors = lda[other_corpus]
for vector in vectors:
    print(vector)

[(0, np.float32(0.050971813)), (1, np.float32(0.050022878)), (2, np.float32(0.052688327)), (3, np.float32(0.7962472)), (4, np.float32(0.050069764))]
[(0, np.float32(0.05265465)), (1, np.float32(0.052030176)), (2, np.float32(0.050034855)), (3, np.float32(0.7951919)), (4, np.float32(0.050088447))]
[(0, np.float32(0.05001559)), (1, np.float32(0.40606645)), (2, np.float32(0.44330558)), (3, np.float32(0.050573677)), (4, np.float32(0.050038725))]


In [25]:
lda.get_topics() # 单词对应的主题向量矩阵

array([[0.03723076, 0.03739299, 0.03774357, 0.03774315, 0.21990743,
        0.03808359, 0.03739828, 0.03742468, 0.03729653, 0.03895876,
        0.22043483, 0.22038546],
       [0.03148139, 0.18607885, 0.0317453 , 0.03173223, 0.03155616,
        0.34089977, 0.03167766, 0.03174051, 0.18627654, 0.03287856,
        0.0322763 , 0.03165675],
       [0.22025612, 0.22011352, 0.21949242, 0.03753324, 0.0373198 ,
        0.03766478, 0.03744627, 0.03732702, 0.0372983 , 0.03951372,
        0.03844494, 0.03758976],
       [0.05632424, 0.00956069, 0.05620239, 0.10273589, 0.0563539 ,
        0.10317083, 0.1028474 , 0.1498832 , 0.05617607, 0.14820862,
        0.10243911, 0.05609763],
       [0.08245422, 0.08282899, 0.08337177, 0.08268172, 0.08252839,
        0.08340985, 0.08281402, 0.0828122 , 0.08298343, 0.08610734,
        0.08517744, 0.08283063]], dtype=float32)

In [26]:
# 查看主题的组成
lda.print_topics()

[(0,
  '0.220*"10" + 0.220*"11" + 0.220*"4" + 0.039*"9" + 0.038*"5" + 0.038*"2" + 0.038*"3" + 0.037*"7" + 0.037*"6" + 0.037*"1"'),
 (1,
  '0.341*"5" + 0.186*"8" + 0.186*"1" + 0.033*"9" + 0.032*"10" + 0.032*"2" + 0.032*"7" + 0.032*"3" + 0.032*"6" + 0.032*"11"'),
 (2,
  '0.220*"0" + 0.220*"1" + 0.219*"2" + 0.040*"9" + 0.038*"10" + 0.038*"5" + 0.038*"11" + 0.038*"3" + 0.037*"6" + 0.037*"7"'),
 (3,
  '0.150*"7" + 0.148*"9" + 0.103*"5" + 0.103*"6" + 0.103*"3" + 0.102*"10" + 0.056*"4" + 0.056*"0" + 0.056*"2" + 0.056*"8"'),
 (4,
  '0.086*"9" + 0.085*"10" + 0.083*"5" + 0.083*"2" + 0.083*"8" + 0.083*"11" + 0.083*"1" + 0.083*"6" + 0.083*"7" + 0.083*"3"')]

In [22]:
# 查看文档属于哪个主题
lda.get_document_topics(common_corpus[0])

[(0, np.float32(0.05002191)),
 (1, np.float32(0.050382752)),
 (2, np.float32(0.79928553)),
 (3, np.float32(0.050270915)),
 (4, np.float32(0.050038867))]

In [16]:
# 更新模型（在当前模型基础上继续更新模型参数）
lda.update(other_corpus)

In [17]:
# 更新后模型结果获取(文本向量)
vectors = lda[other_corpus]
for vector in vectors:
    print(vector)

[(0, np.float32(0.050377715)), (1, np.float32(0.050011378)), (2, np.float32(0.05216704)), (3, np.float32(0.7974078)), (4, np.float32(0.050036073))]
[(0, np.float32(0.050490417)), (1, np.float32(0.05023589)), (2, np.float32(0.050011102)), (3, np.float32(0.79922473)), (4, np.float32(0.05003777))]
[(0, np.float32(0.05001291)), (1, np.float32(0.3979814)), (2, np.float32(0.45161462)), (3, np.float32(0.050368235)), (4, np.float32(0.050022826))]


# 四、Other

官网文档：https://radimrehurek.com/gensim/apiref.html

In [18]:
print("各个单词对应的主题向量:")
word_embedding_tabel = model.get_topics().T
print(type(word_embedding_tabel))
print(word_embedding_tabel.shape)
print(word_embedding_tabel)

各个单词对应的主题向量:
<class 'numpy.ndarray'>
(12, 5)
[[0.03723076 0.03148139 0.22025612 0.05632424 0.08245422]
 [0.03739299 0.18607885 0.22011352 0.00956069 0.08282899]
 [0.03774357 0.0317453  0.21949242 0.05620239 0.08337177]
 [0.03774315 0.03173223 0.03753324 0.10273589 0.08268172]
 [0.21990743 0.03155616 0.0373198  0.0563539  0.08252839]
 [0.03808359 0.34089977 0.03766478 0.10317083 0.08340985]
 [0.03739828 0.03167766 0.03744627 0.1028474  0.08281402]
 [0.03742468 0.03174051 0.03732702 0.1498832  0.0828122 ]
 [0.03729653 0.18627654 0.0372983  0.05617607 0.08298343]
 [0.03895876 0.03287856 0.03951372 0.14820862 0.08610734]
 [0.22043483 0.0322763  0.03844494 0.10243911 0.08517744]
 [0.22038546 0.03165675 0.03758976 0.05609763 0.08283063]]


In [19]:
common_dictionary.token2id

{'computer': 0,
 'human': 1,
 'interface': 2,
 'response': 3,
 'survey': 4,
 'system': 5,
 'time': 6,
 'user': 7,
 'eps': 8,
 'trees': 9,
 'graph': 10,
 'minors': 11}